### ISSUE TITLE
Filter function handles tag's case-sensitivity incorrectly

### ISSUE THREAD

**Issue by zeonchew0324** [AY2425S1-CS2103T-W11-2/tp#162]
Filter function cannot differentiate case-sensitive tags.
Ex:
'filter t/bRide' throws error when 'bride' is added as tag.

**Comment by jiaxinnns** [comment]
If I'm not wrong, tags are already case-insensitive

**Comment by zeonchew0324** [comment]
After testing, I found that tags are indeed case-insensitive, but the filter function does not handle the case-sensitivity well.

**Comment by zeonchew0324** [comment]
I will change my issue description.
