### ISSUE TITLE
Allow filtering of multiple RSVP status

### ISSUE THREAD

**Issue by zeonchew0324** [AY2425S1-CS2103T-W11-2/tp#164]
Should allow filtering of several RSVP status.

Ex: filter s/1 s/2 should provide list of guests coming or guests not coming, instead of specifying only one.

**Comment by SherChew27** [comment]
Rational here is that filtering goes off AND, not OR. If the input is filter s/1 s/2, meaning coming and not coming, there can't be a guest that is coming and not coming, which means that it is a user error.
