### ISSUE TITLE
Add optional use of OR constraints for filter search keywords

### ISSUE THREAD

**Issue by zeonchew0324** [AY2425S1-CS2103T-W11-2/tp#171]
Add functionality for filter:

User has the option to choose using OR constraints for filter. 
Ex. "filter s/1 or t/bride's side" shows users that are tagged with the Rsvp status or the tag. 

This could gives user the option to search for more results.

**Comment by SherChew27** [comment]
Currently, the default predicate is TRUE. If we were to implement OR filtering, it will just return all persons because of the default predicate. Would suggest adding OR filtering to proposed features.
