### ISSUE TITLE
Insufficient Message Displayed to User for Newtag Command

### ISSUE THREAD

**Issue by kvernnn** [AY2425S1-CS2103T-W11-2/tp#184]
<img width="911" alt="image" src="https://github.com/user-attachments/assets/1ec2db61-75a6-4694-ac40-da4016f42f50">

Possible feature flaw
Steps:
1. Ensure a tag already exists in the tag list e.g. existingtag
2. Run command `newtag t/testtag t/existingtag`
3. Error message is shown but no success message for the creation of testtag, though it is being created

**Comment by jiaxinnns** [comment]
Resolved in V1.5
