### ISSUE TITLE
Overzealous Input Validation for Deletetag Command

### ISSUE THREAD

**Issue by kvernnn** [AY2425S1-CS2103T-W11-2/tp#188]
<img width="911" alt="image" src="https://github.com/user-attachments/assets/af8e9ec5-db39-4eb3-a062-22f634918e4f">
Example:
Hyphens, which are commonly used symbols, is treated as an invalid input

**Comment by jiaxinnns** [comment]
Actually should we just allow all ASCII characters to be used? A lot of things seem overzealous at this point and adding more exceptions will cause the message_usage string to become overly long
