### ISSUE TITLE
[PE-D][Tester A] Typo in the example of untag command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-2/tp#244]
Here, "**tag**" is a typo and should be "**untag**", or it may possibly confuse users.

![image.png](https://raw.githubusercontent.com/RuijianLu/ped/main/files/ff253c09-c97d-44cc-9885-2408b2029c26.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: RuijianLu/ped#1

**Comment by jiaxinnns** [comment]
Thanks for pointing it out! However we believe the severity level should be very low as the user would likely have read the entire paragraph before that sentence and it is quite self explanatory
