### ISSUE TITLE
[PE-D][Tester D] Typo : Error message when calling tag command with invalid index

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W11-2/tp#247]
Calling tag command with invalid index, e.g. index = 7 when there are only 6 people.

![image.png](https://raw.githubusercontent.com/sandyk0105/ped/main/files/2951609d-2e95-4ff8-b176-2ce44d955167.png)

The error message:

Index provided is invalid. Index must _bea_ positive integer no greater than the list size!

Should be

Index provided is invalid. Index must _be a_ positive integer no greater than the list size!

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: sandyk0105/ped#2

**Comment by kvernnn** [comment]
Duplicate bug caught. Issue will be closed.
