### ISSUE TITLE
[PE-D][Tester C] `deletetag` command does not return the right error for wrong format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-2/tp#251]
Given `deletetag 1 t/g t/h t/i` with `t/g t/h t/i` as tags in the system: 
I should expect that it gives an command error since the `1` in the command breaks the format of `deletetag [-force] t/TAG1…` therefore I should expect an Invalid command format error but instead I got an tag in use error as shown:

![Screenshot 2024-11-08 at 4.43.21 PM.png](https://raw.githubusercontent.com/rollingpencil/ped/main/files/18c5aa31-f877-4139-96eb-3a2482372cf2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rollingpencil/ped#2

**Comment by jiaxinnns** [comment]
It does not cause inconvenience to the average user as it would not hinder regular use of the app (maybe once at most, when the user is learning the commands for the first time. once the user knows what deletetag is meant for, there is no reason for him/her to continue adding the extra parameter). furthermore he/she can also get instant feedback in the UI (in the tag list panel) when they run deletetag successfully so there is no risk of misunderstanding

 the severity should be low at best
