### ISSUE TITLE
[PE-D][Tester C] `newtag` command should return error for wrong format but command was processed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-2/tp#253]
Given `newtag 1 t/validTag`:
I should expect that the app gives me a command error since the `1` in the command breaks the format of `newtag t/TAG1…` therefore I should expect an Invalid command format error, but instead the command process normally and created the tag
![Screenshot 2024-11-08 at 4.52.01 PM.png](https://raw.githubusercontent.com/rollingpencil/ped/main/files/6e1e6b0d-6a6e-4fda-9639-8dd9dee0073e.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: rollingpencil/ped#3

**Comment by jiaxinnns** [comment]
This is the intended functionality of the app as allowing deviations which do not affect usability of the app would increase the flexibility and tolerance to typos. The user can also get immediate feedback on what was added in the tag list panel  immediately after running the command (not pictured in screenshot), so any misunderstanding would be clarified quickly.

However, we do agree it could have been documented more clearly in the UG
