### ISSUE TITLE
[PE-D][Tester E] Renametag does not rename the tag in filter predicate

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-2/tp#282]
1. `filter t/bug`

![image.png](https://raw.githubusercontent.com/seah-minlong/ped/main/files/e1c6b75c-cc29-4fae-8fbc-d03144ed2cab.png)

2. `renametag t/bug t/hi`. Filter applied is still bug.

![image.png](https://raw.githubusercontent.com/seah-minlong/ped/main/files/769d8ac7-4a01-4164-bf8d-c3d6e3ce4403.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: seah-minlong/ped#16

**Comment by zeonchew0324** [comment]
issue solved
